from weather_app.views.dashboard import *
from weather_app.views.register_user import *
from weather_app.views.login_user import *
from weather_app.views.logout_user import *
from weather_app.views.user_profile import *
from weather_app.views.random_location import *
from weather_app.views.search_location import *
from weather_app.views.update_location import *
from weather_app.views.utils import *
from weather.secrets import *