# Generated by Django 3.2.5 on 2021-09-23 17:39

from django.db import migrations, models
import weather_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='favourite',
            new_name='favorite',
        ),
        migrations.AlterField(
            model_name='location',
            name='label',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
