# Generated by Django 3.2.7 on 2021-10-07 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0003_auto_20211003_2259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='favorite',
            new_name='is_favorite',
        ),
    ]
